#pragma once
#include "intermediate_representation/Function.h"
#include "passes/pass_types/FunctionLevelPass.h"

// This pass now only works with recursion generated by Recursive Functions
// language compiler. Moreover it does not support argmin inside recursive
// function
namespace Passes {
class RecursionToLoopPass : public FunctionLevelPass<> {
 protected:
  std::pair<IR::FunctionCall*, IR::BasicBlock*> find_suitable_call(
      IR::Function& function);

  bool apply(IR::Function& function) override;

  void get_blocks_before_recursive_call(IR::BasicBlock*, const IR::BasicBlock*,
                                        std::unordered_set<IR::BasicBlock*>&);

 public:
  RecursionToLoopPass(PassManager& manager) : FunctionLevelPass(manager) {
    info_.name = "Recursion to loop";
    info_.repeat_while_changing = false;

    info_.preserve_ssa = true;
    info_.require_ssa = true;
  }
};
}  // namespace Passes
