#pragma once
#include "intermediate_representation/Function.h"
#include "passes/pass_types/FunctionLevelPass.h"

// This pass now only works with recursion generated by Recursive Functions
// language compiler. Moreover it does not support argmin inside recursive
// function
namespace Passes {
class RecursionToLoopPass : public FunctionLevelPass<> {
 protected:
  bool apply(IR::Function& function) override;

  void get_blocks_before_recursive_call(IR::BasicBlock*, const IR::BasicBlock*,
                                        std::unordered_set<IR::BasicBlock*>&);

 public:
  using FunctionLevelPass::FunctionLevelPass;
};
}  // namespace Passes
