#pragma once

#include "compilation/CompileTreeBuilder.h"
#include "compilation/Instructions.h"
#include "compilation/bytecode/BytecodeCompiler.h"
#include "execution/BytecodeExecutor.h"
#include "lexis/LexicalAnalyzer.h"
#include "log/Logger.h"
#include "preprocessor/FileSource.h"
#include "preprocessor/Preprocessor.h"
#include "preprocessor/TextSource.h"
#include "syntax/RecursiveFunctionsSyntax.h"
#include "syntax/buffalo/SyntaxConsumers.h"
#include "syntax/buffalo/SyntaxNode.h"
#include "syntax/buffalo/SyntaxTreeBuilder.h"
