name: Run Tests

on:
  push

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Build docker image
        run: docker build -t tlang-dev .
      - name: Run tests inside container
        run: docker run -v $(pwd):/tlang -w /tlang --entrypoint /bin/sh tlang-dev -c ./testing.sh
      - name: Test Report
        uses: dorny/test-reporter@v1
        with:
          name: Test Report
          path: build/unit-report.xml
          reporter: jest-junit