name: Run Tests

on:
  push

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7
        with:
          submodules: 'recursive'
      - name: Build docker image
        run: docker build -t tlang-dev .
      - name: Run tests inside container
        # tests must not run as root, look at tests/unit/sources/SourceManagerTests.cpp to learn more
        run: docker run --user $(id -u):$(id -g) -e HOME=/tmp -v $(pwd):/tlang -w /tlang --entrypoint /bin/sh tlang-dev -c ./testing.sh
      - name: Build examples inside container
        # runs as root because installed tlang reads its files from /usr/local/share/tlang
        run: docker run -v $(pwd):/tlang -w /tlang --entrypoint /bin/sh tlang-dev -c 'cmake --build build -t cli_installation && cmake --install build && for dir in examples/*/; do (cd "$dir" && make main) || exit 1; done'
      - name: Unit Test Report
        uses: dorny/test-reporter@v3
        if: always()
        with:
          name: Unit Test Report (linux)
          path: build/unit-report.xml
          reporter: jest-junit
      - name: Lit Test Report
        uses: dorny/test-reporter@v3
        if: always()
        with:
          name: Lit Test Report (linux)
          path: build/lit-report.xml
          reporter: java-junit

  macos:
    runs-on: macos-26
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7
        with:
          submodules: 'recursive'
      - name: Install LLVM and lit
        run: |
          brew update
          brew install llvm@23
          python3 -m venv ~/lit-venv
          ~/lit-venv/bin/pip install --no-input lit psutil
          echo "$HOME/lit-venv/bin" >> "$GITHUB_PATH"
      - name: Run tests
        run: |
          export LLVM_DIR="$(brew --prefix llvm@23)/lib/cmake/llvm"
          export PATH="$(brew --prefix llvm@23)/bin:$PATH"
          ./testing.sh
      - name: Build examples
        run: |
          export PATH="$(brew --prefix llvm@23)/bin:$PATH"
          cmake --build build -t cli_installation
          sudo cmake --install build
          for dir in examples/*/; do (cd "$dir" && make main) || exit 1; done
      - name: Unit Test Report
        uses: dorny/test-reporter@v3
        if: always()
        with:
          name: Unit Test Report (macos)
          path: build/unit-report.xml
          reporter: jest-junit
      - name: Lit Test Report
        uses: dorny/test-reporter@v3
        if: always()
        with:
          name: Lit Test Report (macos)
          path: build/lit-report.xml
          reporter: java-junit
